//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 03:17:06 PM IST 
//


package com.rssoftware.upiint.schema;

import java.math.BigDecimal;









/**
 * <p>Java class for BeneficiaryFromTransaction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BeneficiaryFromTransaction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="txnRefId" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="txnIndividualAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="beneficiaryId" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="paymentAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="payerPayeeFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="creationTs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */


public class BeneficiaryFromTransaction {

    
    
    
    protected String txnRefId;
    
    protected String name;
    
    protected BigDecimal txnIndividualAmt;
    
    
    
    protected String beneficiaryId;
    
    protected String paymentAddress;
    
    protected String payerPayeeFlag;
    
    protected String creationTs;

    /**
     * Gets the value of the txnRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnRefId() {
        return txnRefId;
    }

    /**
     * Sets the value of the txnRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnRefId(String value) {
        this.txnRefId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the txnIndividualAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTxnIndividualAmt() {
        return txnIndividualAmt;
    }

    /**
     * Sets the value of the txnIndividualAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTxnIndividualAmt(BigDecimal value) {
        this.txnIndividualAmt = value;
    }

    /**
     * Gets the value of the beneficiaryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeneficiaryId() {
        return beneficiaryId;
    }

    /**
     * Sets the value of the beneficiaryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeneficiaryId(String value) {
        this.beneficiaryId = value;
    }

    /**
     * Gets the value of the paymentAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentAddress() {
        return paymentAddress;
    }

    /**
     * Sets the value of the paymentAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentAddress(String value) {
        this.paymentAddress = value;
    }

    /**
     * Gets the value of the payerPayeeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerPayeeFlag() {
        return payerPayeeFlag;
    }

    /**
     * Sets the value of the payerPayeeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerPayeeFlag(String value) {
        this.payerPayeeFlag = value;
    }

    /**
     * Gets the value of the creationTs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationTs() {
        return creationTs;
    }

    /**
     * Sets the value of the creationTs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationTs(String value) {
        this.creationTs = value;
    }

}
