//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 03:17:06 PM IST 
//


package com.rssoftware.upiint.schema;

import java.math.BigInteger;






/**
 * <p>Java class for ConfigElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConfigElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bankPSP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bankCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="publickKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="maxLimit" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */


public class ConfigElement {

    
    protected String bankPSP;
    
    protected String bankCode;
    
    protected String publickKey;
    
    protected BigInteger maxLimit;

    protected String  bankName;

    public String getClMobileNumber() {
        return clMobileNumber;
    }

    public void setClMobileNumber(String clMobileNumber) {
        this.clMobileNumber = clMobileNumber;
    }

    protected String clMobileNumber;

    protected String payValidInSec;

    protected  String collectValidInSec;

    protected  String orgRefUrl;

    public String getOrgRefUrl() {
        return orgRefUrl;
    }

    public void setOrgRefUrl(String orgRefUrl) {
        this.orgRefUrl = orgRefUrl;
    }



    public String getCollectValidInSec() {
        return collectValidInSec;
    }

    public void setCollectValidInSec(String collectValidInSec) {
        this.collectValidInSec = collectValidInSec;
    }



    public String getPayValidInSec() {
        return payValidInSec;
    }

    public void setPayValidInSec(String payValidInSec) {
        this.payValidInSec = payValidInSec;
    }



    public String getK0Hex() {
        return k0Hex;
    }

    public void setK0Hex(String k0Hex) {
        this.k0Hex = k0Hex;
    }

    protected String k0Hex;

    public String getBankName() {
        return bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * Gets the value of the bankPSP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankPSP() {
        return bankPSP;
    }

    /**
     * Sets the value of the bankPSP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankPSP(String value) {
        this.bankPSP = value;
    }

    /**
     * Gets the value of the bankCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * Sets the value of the bankCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankCode(String value) {
        this.bankCode = value;
    }

    /**
     * Gets the value of the publickKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublickKey() {
        return publickKey;
    }

    /**
     * Sets the value of the publickKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublickKey(String value) {
        this.publickKey = value;
    }

    /**
     * Gets the value of the maxLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxLimit() {
        return maxLimit;
    }

    /**
     * Sets the value of the maxLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxLimit(BigInteger value) {
        this.maxLimit = value;
    }

}
