//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 03:17:06 PM IST 
//


package com.rssoftware.upiint.schema;


import java.io.Serializable;

/**
 * <p>Java class for CredentialSubtype.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CredentialSubtype">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="IIR"/>
 *     &lt;enumeration value="FMR"/>
 *     &lt;enumeration value="FIR"/>
 *     &lt;enumeration value="OTP"/>
 *     &lt;enumeration value="SKEY"/>
 *     &lt;enumeration value="SMS"/>
 *     &lt;enumeration value="EMAIL"/>
 *     &lt;enumeration value="HOTP"/>
 *     &lt;enumeration value="TOTP"/>
 *     &lt;enumeration value="MPIN"/>
 *     &lt;enumeration value="CVV1"/>
 *     &lt;enumeration value="CVV2"/>
 *     &lt;enumeration value="EMV"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */


public enum CredentialSubtype implements Serializable{

    IIR("IIR"),
    FMR("FMR"),
    FIR("FIR"),
    OTP("OTP"),
    SKEY("SKEY"),
    SMS("SMS"),
    EMAIL("EMAIL"),
    HOTP("HOTP"),
    TOTP("TOTP"),
    MPIN("MPIN"),
    
    CVV_1("CVV1"),
    
    CVV_2("CVV2"),
    EMV("EMV");
    private final String value;

    CredentialSubtype(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CredentialSubtype fromValue(String v) {
        for (CredentialSubtype c: CredentialSubtype.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
