//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 03:17:06 PM IST 
//


package com.rssoftware.upiint.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;






/**
 * <p>Java class for CredentialMetaData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CredentialMetaData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ownBank" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="credAllowed" type="{http://rssoftware.com/upiint/schema/}CredAllowed" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */


public class CredentialMetaData implements Serializable {

    protected boolean ownBank;
    
    protected List<CredAllowed> credAllowed;

    /**
     * Gets the value of the ownBank property.
     * 
     */
    public boolean isOwnBank() {
        return ownBank;
    }

    /**
     * Sets the value of the ownBank property.
     * 
     */
    public void setOwnBank(boolean value) {
        this.ownBank = value;
    }

    /**
     * Gets the value of the credAllowed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the credAllowed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCredAllowed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CredAllowed }
     * 
     * 
     */
    public List<CredAllowed> getCredAllowed() {
        if (credAllowed == null) {
            credAllowed = new ArrayList<CredAllowed>();
        }
        return this.credAllowed;
    }

}
