//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 03:17:06 PM IST 
//


package com.rssoftware.upiint.schema;

import java.io.Serializable;
import java.math.BigInteger;







/**
 * <p>Java class for CredAllowed complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CredAllowed">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://rssoftware.com/upiint/schema/}CredentialType"/>
 *         &lt;element name="subtype" type="{http://rssoftware.com/upiint/schema/}CredentialSubtype"/>
 *         &lt;element name="dtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dlemgth" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */


public class CredAllowed implements Serializable{

    
    
    protected CredentialType type;
    
    
    protected CredentialSubtype subtype;
    
    protected String dtype;
    
    protected BigInteger dlemgth;





    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link CredentialType }
     *     
     */
    public CredentialType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CredentialType }
     *     
     */
    public void setType(CredentialType value) {
        this.type = value;
    }

    /**
     * Gets the value of the subtype property.
     * 
     * @return
     *     possible object is
     *     {@link CredentialSubtype }
     *     
     */
    public CredentialSubtype getSubtype() {
        return subtype;
    }

    /**
     * Sets the value of the subtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link CredentialSubtype }
     *     
     */
    public void setSubtype(CredentialSubtype value) {
        this.subtype = value;
    }

    /**
     * Gets the value of the dtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtype() {
        return dtype;
    }

    /**
     * Sets the value of the dtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtype(String value) {
        this.dtype = value;
    }

    /**
     * Gets the value of the dlemgth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDlemgth() {
        return dlemgth;
    }

    /**
     * Sets the value of the dlemgth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDlemgth(BigInteger value) {
        this.dlemgth = value;
    }

}
