//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 03:17:06 PM IST 
//


package com.rssoftware.upiint.schema;








/**
 * <p>Java class for EntityRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EntityRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="activity" type="{http://rssoftware.com/upiint/schema/}UserActivity"/>
 *         &lt;element name="EntityInstance" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */


public class EntityRequest {

    
    
    protected UserActivity activity;
    
    protected Object entityInstance;

    /**
     * Gets the value of the activity property.
     * 
     * @return
     *     possible object is
     *     {@link UserActivity }
     *     
     */
    public UserActivity getActivity() {
        return activity;
    }

    /**
     * Sets the value of the activity property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserActivity }
     *     
     */
    public void setActivity(UserActivity value) {
        this.activity = value;
    }

    /**
     * Gets the value of the entityInstance property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEntityInstance() {
        return entityInstance;
    }

    /**
     * Sets the value of the entityInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEntityInstance(Object value) {
        this.entityInstance = value;
    }

}
