//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 03:17:06 PM IST 
//


package com.rssoftware.upiint.schema;





/**
 * <p>Java class for FieldValidationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FieldValidationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NOT_NULL"/>
 *     &lt;enumeration value="NOT_EMPTY"/>
 *     &lt;enumeration value="PATTEREN"/>
 *     &lt;enumeration value="MIN_LENGTH"/>
 *     &lt;enumeration value="MAX_LENGTH"/>
 *     &lt;enumeration value="MIN_VAL"/>
 *     &lt;enumeration value="MAX_VAL"/>
 *     &lt;enumeration value="OBJECT_VALIDATION"/>
 *     &lt;enumeration value="LIST_VALIDATION"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */


public enum FieldValidationType {

    NOT_NULL,
    NOT_EMPTY,
    PATTEREN,
    MIN_LENGTH,
    MAX_LENGTH,
    MIN_VAL,
    MAX_VAL,
    OBJECT_VALIDATION,
    LIST_VALIDATION;

    public String value() {
        return name();
    }

    public static FieldValidationType fromValue(String v) {
        return valueOf(v);
    }

}
