//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 03:17:06 PM IST 
//


package com.rssoftware.upiint.schema;


import java.math.BigInteger;

/**
 * <p>Java class for ListParm complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ListParm">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ownerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vpa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="txnRefId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fetchActiveOnly" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="parmType" type="{http://rssoftware.com/upiint/schema/}UserEntityType"/>
 *          &lt;element name="meba" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */


public class ListParm {


    protected String userId;

    protected String ownerId;

    protected String vpa;

    protected String txnRefId;

    protected String mode;
    protected boolean fetchActiveOnly;


    protected String ifsc;
    protected String referanceId;
    protected BigInteger waitingTime;
    protected String validUpto;
    protected boolean meba;
    protected String fromDate;
    protected String toDate;

    public String getCustRefId() {
        return custRefId;
    }

    public void setCustRefId(String custRefId) {
        this.custRefId = custRefId;
    }

    protected String custRefId;

    public String getFromDate() {
        return fromDate;
    }

    public void setFromDate(String fromDate) {
        this.fromDate = fromDate;
    }

    public String getToDate() {
        return toDate;
    }

    public void setToDate(String toDate) {
        this.toDate = toDate;
    }



    public boolean getMeba() {
        return meba;
    }

    public void setMeba(boolean meba) {
        this.meba = meba;
    }


    public String getValidUpto() {
        return validUpto;
    }

    public void setValidUpto(String validUpto) {
        this.validUpto = validUpto;
    }

    public BigInteger getWaitingTime() {
        return waitingTime;
    }

    public void setWaitingTime(BigInteger waitingTime) {
        this.waitingTime = waitingTime;
    }


    public String getReferanceId() {
        return referanceId;
    }

    public void setReferanceId(String referanceId) {
        this.referanceId = referanceId;
    }


    public String getIfsc() {
        return ifsc;
    }

    public void setIfsc(String ifsc) {
        this.ifsc = ifsc;
    }


    protected UserEntityType parmType;

    /**
     * Gets the value of the userId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the ownerId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * Sets the value of the ownerId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOwnerId(String value) {
        this.ownerId = value;
    }

    /**
     * Gets the value of the vpa property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVpa() {
        return vpa;
    }

    /**
     * Sets the value of the vpa property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVpa(String value) {
        this.vpa = value;
    }

    /**
     * Gets the value of the txnRefId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTxnRefId() {
        return txnRefId;
    }

    /**
     * Sets the value of the txnRefId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTxnRefId(String value) {
        this.txnRefId = value;
    }

    /**
     * Gets the value of the mode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMode(String value) {
        this.mode = value;
    }

    /**
     * Gets the value of the fetchActiveOnly property.
     */
    public boolean isFetchActiveOnly() {
        return fetchActiveOnly;
    }

    /**
     * Sets the value of the fetchActiveOnly property.
     */
    public void setFetchActiveOnly(boolean value) {
        this.fetchActiveOnly = value;
    }

    /**
     * Gets the value of the parmType property.
     *
     * @return possible object is
     * {@link UserEntityType }
     */
    public UserEntityType getParmType() {
        return parmType;
    }

    /**
     * Sets the value of the parmType property.
     *
     * @param value allowed object is
     *              {@link UserEntityType }
     */
    public void setParmType(UserEntityType value) {
        this.parmType = value;
    }

}
