//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 03:17:06 PM IST 
//


package com.rssoftware.upiint.schema;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for TransactionHistory complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="TransactionHistory">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="eventType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */


public class Notifications {


    protected String message;
    protected String status;
    protected String userId;
    protected String date;
    protected String eventType;

    /**
     * Gets the value of the userId.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId.
     *
     * @param userId allowed object is
     *               {@link String }
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * Gets the value of the message.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message.
     *
     * @param message allowed object is
     *                {@link String }
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Gets the value of the status.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status.
     *
     * @param status allowed object is
     *               {@link String }
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Gets the value of the date.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date.
     *
     * @param date allowed object is
     *             {@link String }
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * Gets the value of the event type.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * Sets the value of the event type.
     *
     * @param eventType allowed object is
     *                  {@link String }
     */
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }


}
