//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.17 at 04:14:17 PM IST 
//


package com.rssoftware.upiint.schema;

import java.io.Serializable;



/**
 * <p>Java class for OtpRequest complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="OtpRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="otpTxnId" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="paymentTxnId" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="operation" type="{http://rssoftware.com/upiint/schema/}OtpRequestType"/>
 *         &lt;element name="payer" type="{http://rssoftware.com/upiint/schema/}Payer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
public class OtpRequest
        implements Serializable
{

    private final static long serialVersionUID = -1L;
    protected String otpTxnId;
    protected String paymentTxnId;
    protected OtpRequestType operation;
    protected Payer payer;

    /**
     * Gets the value of the otpTxnId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOtpTxnId() {
        return otpTxnId;
    }

    /**
     * Sets the value of the otpTxnId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOtpTxnId(String value) {
        this.otpTxnId = value;
    }

    /**
     * Gets the value of the paymentTxnId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPaymentTxnId() {
        return paymentTxnId;
    }

    /**
     * Sets the value of the paymentTxnId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPaymentTxnId(String value) {
        this.paymentTxnId = value;
    }

    /**
     * Gets the value of the operation property.
     *
     * @return
     *     possible object is
     *     {@link OtpRequestType }
     *
     */
    public OtpRequestType getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     *
     * @param value
     *     allowed object is
     *     {@link OtpRequestType }
     *
     */
    public void setOperation(OtpRequestType value) {
        this.operation = value;
    }

    /**
     * Gets the value of the payer property.
     *
     * @return
     *     possible object is
     *     {@link Payer }
     *
     */
    public Payer getPayer() {
        return payer;
    }

    /**
     * Sets the value of the payer property.
     *
     * @param value
     *     allowed object is
     *     {@link Payer }
     *
     */
    public void setPayer(Payer value) {
        this.payer = value;
    }

}
