//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 03:17:06 PM IST 
//


package com.rssoftware.upiint.schema;

import java.math.BigDecimal;
import java.math.BigInteger;









/**
 * <p>Java class for Payee complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Payee">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="txnPayeeID" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="payeeUserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="payeeAcVpa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="payeeAcNickName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bankAcNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bankAcType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ifsc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Aadhaar" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AadhaarIin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mobile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mmid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="payeeAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="payeeAmtCurrency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="payeeStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="payeeErrorCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="cbsApprovalNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reversalTxnRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reversalTxnAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="cbsReversalApprovalNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */


public class Payee {

    
    
    
    protected String txnPayeeID;
    
    protected String payeeUserId;
    
    protected String name;
    
    protected String payeeAcVpa;
    
    protected String payeeAcNickName;
    
    protected String bankAcNumber;
    
    protected String bankAcType;
    
    protected String ifsc;
    
    protected String aadhaar;
    
    protected String aadhaarIin;
    
    protected String mobile;
    
    protected String mmid;
    
    protected BigDecimal payeeAmt;
    
    protected String payeeAmtCurrency;
    
    protected String payeeStatus;
    
    protected String payeeErrorCode;
    
    protected BigInteger index;
    
    protected String cbsApprovalNum;
    
    protected String reversalTxnRef;
    
    protected BigDecimal reversalTxnAmt;
    
    protected String cbsReversalApprovalNum;

    /**
     * Gets the value of the txnPayeeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnPayeeID() {
        return txnPayeeID;
    }

    /**
     * Sets the value of the txnPayeeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnPayeeID(String value) {
        this.txnPayeeID = value;
    }

    /**
     * Gets the value of the payeeUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayeeUserId() {
        return payeeUserId;
    }

    /**
     * Sets the value of the payeeUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayeeUserId(String value) {
        this.payeeUserId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the payeeAcVpa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayeeAcVpa() {
        return payeeAcVpa;
    }

    /**
     * Sets the value of the payeeAcVpa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayeeAcVpa(String value) {
        this.payeeAcVpa = value;
    }

    /**
     * Gets the value of the payeeAcNickName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayeeAcNickName() {
        return payeeAcNickName;
    }

    /**
     * Sets the value of the payeeAcNickName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayeeAcNickName(String value) {
        this.payeeAcNickName = value;
    }

    /**
     * Gets the value of the bankAcNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankAcNumber() {
        return bankAcNumber;
    }

    /**
     * Sets the value of the bankAcNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankAcNumber(String value) {
        this.bankAcNumber = value;
    }

    /**
     * Gets the value of the bankAcType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankAcType() {
        return bankAcType;
    }

    /**
     * Sets the value of the bankAcType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankAcType(String value) {
        this.bankAcType = value;
    }

    /**
     * Gets the value of the ifsc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIfsc() {
        return ifsc;
    }

    /**
     * Sets the value of the ifsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIfsc(String value) {
        this.ifsc = value;
    }

    /**
     * Gets the value of the aadhaar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAadhaar() {
        return aadhaar;
    }

    /**
     * Sets the value of the aadhaar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAadhaar(String value) {
        this.aadhaar = value;
    }

    /**
     * Gets the value of the aadhaarIin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAadhaarIin() {
        return aadhaarIin;
    }

    /**
     * Sets the value of the aadhaarIin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAadhaarIin(String value) {
        this.aadhaarIin = value;
    }

    /**
     * Gets the value of the mobile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * Sets the value of the mobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobile(String value) {
        this.mobile = value;
    }

    /**
     * Gets the value of the mmid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMmid() {
        return mmid;
    }

    /**
     * Sets the value of the mmid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMmid(String value) {
        this.mmid = value;
    }

    /**
     * Gets the value of the payeeAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPayeeAmt() {
        return payeeAmt;
    }

    /**
     * Sets the value of the payeeAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPayeeAmt(BigDecimal value) {
        this.payeeAmt = value;
    }

    /**
     * Gets the value of the payeeAmtCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayeeAmtCurrency() {
        return payeeAmtCurrency;
    }

    /**
     * Sets the value of the payeeAmtCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayeeAmtCurrency(String value) {
        this.payeeAmtCurrency = value;
    }

    /**
     * Gets the value of the payeeStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayeeStatus() {
        return payeeStatus;
    }

    /**
     * Sets the value of the payeeStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayeeStatus(String value) {
        this.payeeStatus = value;
    }

    /**
     * Gets the value of the payeeErrorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayeeErrorCode() {
        return payeeErrorCode;
    }

    /**
     * Sets the value of the payeeErrorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayeeErrorCode(String value) {
        this.payeeErrorCode = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIndex(BigInteger value) {
        this.index = value;
    }

    /**
     * Gets the value of the cbsApprovalNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCbsApprovalNum() {
        return cbsApprovalNum;
    }

    /**
     * Sets the value of the cbsApprovalNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCbsApprovalNum(String value) {
        this.cbsApprovalNum = value;
    }

    /**
     * Gets the value of the reversalTxnRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReversalTxnRef() {
        return reversalTxnRef;
    }

    /**
     * Sets the value of the reversalTxnRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReversalTxnRef(String value) {
        this.reversalTxnRef = value;
    }

    /**
     * Gets the value of the reversalTxnAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getReversalTxnAmt() {
        return reversalTxnAmt;
    }

    /**
     * Sets the value of the reversalTxnAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setReversalTxnAmt(BigDecimal value) {
        this.reversalTxnAmt = value;
    }

    /**
     * Gets the value of the cbsReversalApprovalNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCbsReversalApprovalNum() {
        return cbsReversalApprovalNum;
    }

    /**
     * Sets the value of the cbsReversalApprovalNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCbsReversalApprovalNum(String value) {
        this.cbsReversalApprovalNum = value;
    }

}
