//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 03:17:06 PM IST 
//


package com.rssoftware.upiint.schema;

import java.math.BigInteger;






/**
 * <p>Java class for PspBankList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PspBankList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accPvdId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="accPvdName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accPvdIin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accPvdIfsc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */


public class PspBankList {

    
    protected BigInteger accPvdId;
    
    protected String accPvdName;
    
    protected String accPvdIin;
    
    protected String accPvdIfsc;
    
    protected String status;

    public String getMobRegFormat() {
        return mobRegFormat;
    }

    public void setMobRegFormat(String mobRegFormat) {
        this.mobRegFormat = mobRegFormat;
    }

    protected String mobRegFormat;

    /**
     * Gets the value of the accPvdId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAccPvdId() {
        return accPvdId;
    }

    /**
     * Sets the value of the accPvdId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAccPvdId(BigInteger value) {
        this.accPvdId = value;
    }

    /**
     * Gets the value of the accPvdName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccPvdName() {
        return accPvdName;
    }

    /**
     * Sets the value of the accPvdName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccPvdName(String value) {
        this.accPvdName = value;
    }

    /**
     * Gets the value of the accPvdIin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccPvdIin() {
        return accPvdIin;
    }

    /**
     * Sets the value of the accPvdIin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccPvdIin(String value) {
        this.accPvdIin = value;
    }

    /**
     * Gets the value of the accPvdIfsc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccPvdIfsc() {
        return accPvdIfsc;
    }

    /**
     * Sets the value of the accPvdIfsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccPvdIfsc(String value) {
        this.accPvdIfsc = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
