//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 03:17:06 PM IST 
//


package com.rssoftware.upiint.schema;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;









/**
 * <p>Java class for ReqRegMobile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReqRegMobile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ownerId" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="cardDigit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="expDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ifsc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="creds" type="{http://rssoftware.com/upiint/schema/}Cred" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="txnId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */


public class ReqRegMobile {

    
    
    
    protected String ownerId;
    
    protected String cardDigit;
    
    protected String expDate;
    
    protected String ifsc;
    protected List<Cred> creds;

    protected String txnId;

    protected String mobile;
    protected String vpa;

    protected String accNo;

    protected String otpCredDataType;
    protected int otpCredLength;

    public String getOtpCredDataType() {
        return otpCredDataType;
    }

    public void setOtpCredDataType(String otpCredDataType) {
        this.otpCredDataType = otpCredDataType;
    }

    public int getOtpCredLength() {
        return otpCredLength;
    }

    public void setOtpCredLength(int otpCredLength) {
        this.otpCredLength = otpCredLength;
    }

    public BigInteger getWaitingTime() {
        return waitingTime;
    }

    public void setWaitingTime(BigInteger waitingTime) {
        this.waitingTime = waitingTime;
    }

    protected BigInteger waitingTime;

    public String getAccType() {
        return accType;
    }

    public void setAccType(String accType) {
        this.accType = accType;
    }

    protected String accType;

    public LinkAccountDetails getLinkAccountDetails() {
        return linkAccountDetails;
    }

    public void setLinkAccountDetails(LinkAccountDetails linkAccountDetails) {
        this.linkAccountDetails = linkAccountDetails;
    }

    protected LinkAccountDetails linkAccountDetails;

    public String getMobRegFormat() {
        return mobRegFormat;
    }

    public void setMobRegFormat(String mobRegFormat) {
        this.mobRegFormat = mobRegFormat;
    }

    protected String mobRegFormat;

    public String getAccNo() {
        return accNo;
    }

    public void setAccNo(String accNo) {
        this.accNo = accNo;
    }




    //protected CredAllowed credAllowed;

    private IStateListener iStateListener;

    protected String bank_name="";

    public String getBank_name() {
        return bank_name;
    }

    public void setBank_name(String bank_name) {
        this.bank_name = bank_name;
    }

    public IStateListener getiStateListener() {
        return iStateListener;
    }

    public void setiStateListener(IStateListener iStateListener) {
        this.iStateListener = iStateListener;
    }

//    public CredAllowed getCredAllowed() {
//        return credAllowed;
//    }

//    public void setCredAllowed(CredAllowed credAllowed) {
//        this.credAllowed = credAllowed;
//    }


    /**
     * Gets the value of the ownerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * Sets the value of the ownerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerId(String value) {
        this.ownerId = value;
    }

    /**
     * Gets the value of the cardDigit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardDigit() {
        return cardDigit;
    }

    /**
     * Sets the value of the cardDigit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardDigit(String value) {
        this.cardDigit = value;
    }

    /**
     * Gets the value of the expDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpDate() {
        return expDate;
    }

    /**
     * Sets the value of the expDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpDate(String value) {
        this.expDate = value;
    }

    /**
     * Gets the value of the ifsc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIfsc() {
        return ifsc;
    }

    /**
     * Sets the value of the ifsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIfsc(String value) {
        this.ifsc = value;
    }

    /**
     * Gets the value of the creds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Cred }
     * 
     * 
     */
    public List<Cred> getCreds() {
        if (creds == null) {
            creds = new ArrayList<Cred>();
        }
        return this.creds;
    }

    /**
     * Gets the value of the txnId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnId() {
        return txnId;
    }

    /**
     * Sets the value of the txnId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnId(String value) {
        this.txnId = value;
    }



    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getVpa() {
        return vpa;
    }

    public void setVpa(String vpa) {
        this.vpa = vpa;
    }

}
