//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 03:17:06 PM IST 
//


package com.rssoftware.upiint.schema;

import java.util.ArrayList;
import java.util.List;








/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="txnId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vaeList" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Vae" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="vaeName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="vaeAddr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="vaeLogo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="vaeUrl" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="operation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */



public class RequestManageVae {

    
    protected String txnId;
    
    protected List<VaeList> vaeList;

    /**
     * Gets the value of the txnId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnId() {
        return txnId;
    }

    /**
     * Sets the value of the txnId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnId(String value) {
        this.txnId = value;
    }

    /**
     * Gets the value of the vaeList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vaeList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVaeList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VaeList }
     * 
     * 
     */
    public List<VaeList> getVaeList() {
        if (vaeList == null) {
            vaeList = new ArrayList<VaeList>();
        }
        return this.vaeList;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Vae" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="vaeName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="vaeAddr" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="vaeLogo" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="vaeUrl" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="operation" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    
    
    public static class VaeList {

        
        protected List<Vae> vae;

        /**
         * Gets the value of the vae property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vae property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVae().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Vae }
         * 
         * 
         */
        public List<Vae> getVae() {
            if (vae == null) {
                vae = new ArrayList<Vae>();
            }
            return this.vae;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="vaeName" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="vaeAddr" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="vaeLogo" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="vaeUrl" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="operation" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        
        
        public static class Vae {

            
            protected String vaeName;
            
            protected String vaeAddr;
            
            protected String vaeLogo;
            
            protected String vaeUrl;
            
            protected String operation;

            /**
             * Gets the value of the vaeName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVaeName() {
                return vaeName;
            }

            /**
             * Sets the value of the vaeName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVaeName(String value) {
                this.vaeName = value;
            }

            /**
             * Gets the value of the vaeAddr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVaeAddr() {
                return vaeAddr;
            }

            /**
             * Sets the value of the vaeAddr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVaeAddr(String value) {
                this.vaeAddr = value;
            }

            /**
             * Gets the value of the vaeLogo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVaeLogo() {
                return vaeLogo;
            }

            /**
             * Sets the value of the vaeLogo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVaeLogo(String value) {
                this.vaeLogo = value;
            }

            /**
             * Gets the value of the vaeUrl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVaeUrl() {
                return vaeUrl;
            }

            /**
             * Sets the value of the vaeUrl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVaeUrl(String value) {
                this.vaeUrl = value;
            }

            /**
             * Gets the value of the operation property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOperation() {
                return operation;
            }

            /**
             * Sets the value of the operation property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOperation(String value) {
                this.operation = value;
            }

        }

    }

}
