//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 03:17:06 PM IST 
//


package com.rssoftware.upiint.schema;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;









/**
 * <p>Java class for RequestListAccount complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestListAccount">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="linkAccountId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="mobileNumberLink" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="accountNumber" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="ifsc" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="ownerId" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="creds" type="{http://rssoftware.com/upiint/schema/}Cred" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */


public class RequestListAccount {

    
    protected BigInteger linkAccountId;
    
    
    
    protected String mobileNumberLink;
    
    
    
    protected String accountNumber;
    
    
    
    protected String ifsc;
    
    
    
    protected String ownerId;
    protected List<Cred> creds;

    /**
     * Gets the value of the linkAccountId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLinkAccountId() {
        return linkAccountId;
    }

    /**
     * Sets the value of the linkAccountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLinkAccountId(BigInteger value) {
        this.linkAccountId = value;
    }

    /**
     * Gets the value of the mobileNumberLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileNumberLink() {
        return mobileNumberLink;
    }

    /**
     * Sets the value of the mobileNumberLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileNumberLink(String value) {
        this.mobileNumberLink = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the ifsc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIfsc() {
        return ifsc;
    }

    /**
     * Sets the value of the ifsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIfsc(String value) {
        this.ifsc = value;
    }

    /**
     * Gets the value of the ownerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * Sets the value of the ownerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerId(String value) {
        this.ownerId = value;
    }

    /**
     * Gets the value of the creds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Cred }
     * 
     * 
     */
    public List<Cred> getCreds() {
        if (creds == null) {
            creds = new ArrayList<Cred>();
        }
        return this.creds;
    }

}
