//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 03:17:06 PM IST 
//


package com.rssoftware.upiint.schema;

import java.math.BigDecimal;









/**
 * <p>Java class for TransactionAuthRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionAuthRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="upiTxnId" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="initiatedBy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="creationTs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="txnStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="txnIndividualAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="curruency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="paymentAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="payerPayeeFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */


public class TransactionAuthRequest {

    
    
    
    protected String upiTxnId;
    
    protected String initiatedBy;
    
    protected String note;
    
    protected String creationTs;
    
    protected String txnStatus;
    
    protected String userId;
    
    protected String name;
    
    protected BigDecimal txnIndividualAmt;
    
    protected String curruency;
    
    protected String paymentAddress;
    
    protected String payerPayeeFlag;

    protected String payeeAddress;

    protected String payeeName;

    /**
     * Gets the value of the upiTxnId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpiTxnId() {
        return upiTxnId;
    }

    /**
     * Sets the value of the upiTxnId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpiTxnId(String value) {
        this.upiTxnId = value;
    }

    /**
     * Gets the value of the initiatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitiatedBy() {
        return initiatedBy;
    }

    /**
     * Sets the value of the initiatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitiatedBy(String value) {
        this.initiatedBy = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the creationTs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationTs() {
        return creationTs;
    }

    /**
     * Sets the value of the creationTs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationTs(String value) {
        this.creationTs = value;
    }

    /**
     * Gets the value of the txnStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnStatus() {
        return txnStatus;
    }

    /**
     * Sets the value of the txnStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnStatus(String value) {
        this.txnStatus = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the txnIndividualAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTxnIndividualAmt() {
        return txnIndividualAmt;
    }

    /**
     * Sets the value of the txnIndividualAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTxnIndividualAmt(BigDecimal value) {
        this.txnIndividualAmt = value;
    }

    /**
     * Gets the value of the curruency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurruency() {
        return curruency;
    }

    /**
     * Sets the value of the curruency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurruency(String value) {
        this.curruency = value;
    }

    /**
     * Gets the value of the paymentAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentAddress() {
        return paymentAddress;
    }

    /**
     * Sets the value of the paymentAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentAddress(String value) {
        this.paymentAddress = value;
    }

    /**
     * Gets the value of the payerPayeeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerPayeeFlag() {
        return payerPayeeFlag;
    }

    /**
     * Sets the value of the payerPayeeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerPayeeFlag(String value) {
        this.payerPayeeFlag = value;
    }

    /**
     *
     * @return
     */
    public String getPayeeAddress() {
        return payeeAddress;
    }

    /**
     *
     * @param payeeAddress
     */
    public void setPayeeAddress(String payeeAddress) {
        this.payeeAddress = payeeAddress;
    }

    public String getPayeeName() {
        return payeeName;
    }

    public void setPayeeName(String payeeName) {
        this.payeeName = payeeName;
    }
}
