//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 03:17:06 PM IST 
//


package com.rssoftware.upiint.schema;








/**
 * <p>Java class for UserValidation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserValidation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userVPA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="acctNickName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="valType" type="{http://rssoftware.com/upiint/schema/}ValidationType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */


public class UserValidation {

    
    protected String userId;
    
    protected String userVPA;
    
    protected String acctNickName;
    
    
    protected ValidationType valType;

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the userVPA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserVPA() {
        return userVPA;
    }

    /**
     * Sets the value of the userVPA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserVPA(String value) {
        this.userVPA = value;
    }

    /**
     * Gets the value of the acctNickName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctNickName() {
        return acctNickName;
    }

    /**
     * Sets the value of the acctNickName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctNickName(String value) {
        this.acctNickName = value;
    }

    /**
     * Gets the value of the valType property.
     * 
     * @return
     *     possible object is
     *     {@link ValidationType }
     *     
     */
    public ValidationType getValType() {
        return valType;
    }

    /**
     * Sets the value of the valType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidationType }
     *     
     */
    public void setValType(ValidationType value) {
        this.valType = value;
    }

}
