//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 03:17:06 PM IST 
//


package com.rssoftware.upiint.schema;

import java.math.BigDecimal;
import java.math.BigInteger;









/**
 * <p>Java class for UserPayCollScheduleResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserPayCollScheduleResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="schdId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="schdType" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="schdName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ownerId" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="ownVpa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="otherVpa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="frequncy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="recurDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="recurFreq" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="startTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="notifyDays" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */


public class UserPayCollScheduleResponse {

    
    protected BigInteger schdId;
    
    
    
    protected String schdType;
    
    protected String schdName;
    
    
    
    protected String ownerId;
    
    protected String ownVpa;
    
    protected String otherVpa;
    
    protected BigDecimal amount;
    
    protected String frequncy;
    
    protected String status;
    
    protected String recurDate;
    
    protected BigInteger recurFreq;
    
    protected String startDate;
    
    protected String startTime;
    
    protected BigInteger notifyDays;

    /**
     * Gets the value of the schdId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSchdId() {
        return schdId;
    }

    /**
     * Sets the value of the schdId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSchdId(BigInteger value) {
        this.schdId = value;
    }

    /**
     * Gets the value of the schdType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchdType() {
        return schdType;
    }

    /**
     * Sets the value of the schdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchdType(String value) {
        this.schdType = value;
    }

    /**
     * Gets the value of the schdName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchdName() {
        return schdName;
    }

    /**
     * Sets the value of the schdName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchdName(String value) {
        this.schdName = value;
    }

    /**
     * Gets the value of the ownerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * Sets the value of the ownerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerId(String value) {
        this.ownerId = value;
    }

    /**
     * Gets the value of the ownVpa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnVpa() {
        return ownVpa;
    }

    /**
     * Sets the value of the ownVpa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnVpa(String value) {
        this.ownVpa = value;
    }

    /**
     * Gets the value of the otherVpa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherVpa() {
        return otherVpa;
    }

    /**
     * Sets the value of the otherVpa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherVpa(String value) {
        this.otherVpa = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the frequncy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequncy() {
        return frequncy;
    }

    /**
     * Sets the value of the frequncy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequncy(String value) {
        this.frequncy = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the recurDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecurDate() {
        return recurDate;
    }

    /**
     * Sets the value of the recurDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecurDate(String value) {
        this.recurDate = value;
    }

    /**
     * Gets the value of the recurFreq property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRecurFreq() {
        return recurFreq;
    }

    /**
     * Sets the value of the recurFreq property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRecurFreq(BigInteger value) {
        this.recurFreq = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTime(String value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the notifyDays property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNotifyDays() {
        return notifyDays;
    }

    /**
     * Sets the value of the notifyDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNotifyDays(BigInteger value) {
        this.notifyDays = value;
    }

}
