//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 03:17:06 PM IST 
//


package com.rssoftware.upiint.schema;





/**
 * <p>Java class for UserActivity.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UserActivity">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="REGISTER"/>
 *     &lt;enumeration value="FETCH"/>
 *     &lt;enumeration value="UPDATE"/>
 *     &lt;enumeration value="ACTIVATE_USER"/>
 *     &lt;enumeration value="ACIVATE"/>
 *     &lt;enumeration value="DEACIVATE"/>
 *     &lt;enumeration value="OTP_CREATE"/>
 *     &lt;enumeration value="OTP_VALIDATE"/>
 *     &lt;enumeration value="CHANGE_PASSWORD"/>
 *     &lt;enumeration value="FORGOT_PASSWORD"/>
 *     &lt;enumeration value="OTP_FORGOT_PASSWORD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */


public enum UserActivity {

    REGISTER,
    FETCH,
    UPDATE,
    ACTIVATE_USER,
    ACIVATE,
    DEACIVATE,
    OTP_CREATE,
    OTP_VALIDATE,
    CHANGE_PASSWORD,
    FORGOT_PASSWORD,
    OTP_FORGOT_PASSWORD;

    public String value() {
        return name();
    }

    public static UserActivity fromValue(String v) {
        return valueOf(v);
    }

}
