//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 03:17:06 PM IST 
//


package com.rssoftware.upiint.schema;

import java.math.BigDecimal;
import java.util.Date;


/**
 * <p>Java class for UserView complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserView">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userMobile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="identity" type="{http://rssoftware.com/upiint/schema/}Identity"/>
 *         &lt;element name="userEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userMaxPayLimit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="userStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */


public class UserView {

    
    
    
    protected String userId;
    
    protected String userName;
    
    protected String userMobile;
    
    protected Identity identity;
    
    protected String userEmail;
    
    protected String userAddress;
    
    protected BigDecimal userMaxPayLimit;
    
    protected String userStatus;
    protected Device device;

    protected String defaultVpa;

    protected String clToken;

    protected Date clTokenRegistrationDate;

    public String getLastLoginTs() {
        return lastLoginTs;
    }

    public void setLastLoginTs(String lastLoginTs) {
        this.lastLoginTs = lastLoginTs;
    }

    protected String lastLoginTs;

    public String getMrchCode() {
        return mrchCode;
    }

    public void setMrchCode(String mrchCode) {
        this.mrchCode = mrchCode;
    }

    public String getAggrCode() {
        return aggrCode;
    }

    public void setAggrCode(String aggrCode) {
        this.aggrCode = aggrCode;
    }

    protected String mrchCode;
    protected String aggrCode;


    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the userMobile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * Sets the value of the userMobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserMobile(String value) {
        this.userMobile = value;
    }

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link Identity }
     *     
     */
    public Identity getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identity }
     *     
     */
    public void setIdentity(Identity value) {
        this.identity = value;
    }

    /**
     * Gets the value of the userEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * Sets the value of the userEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserEmail(String value) {
        this.userEmail = value;
    }

    /**
     * Gets the value of the userAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * Sets the value of the userAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserAddress(String value) {
        this.userAddress = value;
    }

    /**
     * Gets the value of the userMaxPayLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUserMaxPayLimit() {
        return userMaxPayLimit;
    }

    /**
     * Sets the value of the userMaxPayLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUserMaxPayLimit(BigDecimal value) {
        this.userMaxPayLimit = value;
    }

    /**
     * Gets the value of the userStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * Sets the value of the userStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserStatus(String value) {
        this.userStatus = value;
    }


    /**
     * Gets the value of the device property.
     *
     * @return
     *     possible object is
     *     {@link Device }
     *
     */
    public Device getDevice() {
        return device;
    }

    /**
     * Sets the value of the device property.
     *
     * @param value
     *     allowed object is
     *     {@link Device }
     *
     */
    public void setDevice(Device value) {
        this.device = value;
    }

    public String getDefaultVpa() {
        return defaultVpa;
    }

    public void setDefaultVpa(String defaultVpa) {
        this.defaultVpa = defaultVpa;
    }

    public String getClToken() {
        return clToken;
    }

    public void setClToken(String clToken) {
        this.clToken = clToken;
    }

    public Date getClTokenRegistrationDate() {
        return clTokenRegistrationDate;
    }

    public void setClTokenRegistrationDate(Date clTokenRegistrationDate) {
        this.clTokenRegistrationDate = clTokenRegistrationDate;
    }
}
